# Generated by Django 6.0.5 on 2026-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_index',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='box',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
