# Generated by Django 6.0.5 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_box_box_index_box_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sync_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
