# Generated by Django 6.0.5 on 2026-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_device_sync_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
